/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.*;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import net.miginfocom.swing.MigLayout;
import raven.glasspanepopup.GlassPanePopup;

/**
 *
 * @author Ernesto
 */
public class Message extends javax.swing.JPanel {

    /**
     * Creates new form Message
     */
    public Message() {
        initComponents();
        setOpaque(false);
        init();
    }
    
    /**
     * Initialize all the components needed in order to make the style of the panel.
     */
    private void init(){
        // Set the layout
        setLayout(new MigLayout("wrap,fillx,insets 25 30 30 45","fill,250:280"));
        
        // Set background color
        setBackground(Color.GRAY);
        putClientProperty(FlatClientProperties.STYLE,
                "[light]background:darken(@background,3%);" +
                "[dark]background:lighten(@background,3%)"
        );
        title = new JLabel("An error has occured!");
        
        // Center the title
        centerText(title);
        title.putClientProperty(FlatClientProperties.STYLE, 
                "font:bold +4;"
        );
        
        description = new JLabel("The user does not exist!");
        // Center the text error
        centerText(description);
        
        description.setForeground(Color.GRAY);
        description.putClientProperty(FlatClientProperties.STYLE, 
                "font:bold +3;"
        );
        
        cmdConfirm = new JButton("OK");
        cmdConfirm.putClientProperty(FlatClientProperties.STYLE, 
                "[light]background:darken(@background,10%);" +
                "[dark]background:lighten(@background,10%);" +
                "borderWidth:0;" +
                "focusWidth:0;" +
                 "font:bold +2;" +
                "innerFocusWidth:0"
         );
        cmdConfirm.addActionListener(e -> {
            GlassPanePopup.closePopupAll();
        });
        add(title);
        add(description);
        add(cmdConfirm, "gapy 10");
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2D = (Graphics2D) g.create();
        
        g2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2D.setColor(new Color(46, 46, 46));
        g2D.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2D.dispose();
        
        super.paintComponent(g);
    }
    
    /**
     * This method will center the component
     * given as a parameter.
     * 
     * @param label
     */
    private void centerText(JLabel label){
        // Center the text error
        label.setHorizontalAlignment(SwingConstants.CENTER);  // Horizontal alignment
        label.setVerticalAlignment(SwingConstants.CENTER); // Vertical alignment
    }
    
    /**
     * Set the title of the message that will be displayed on the screen.
     * @param text
     */
    public void setTitle(String text){
        title.setText(text);
    }
    
    /**
     * Set the description of the error that has occured which will be
     * displayed under the title.
     * @param text
     */
    public void setDescription(String text){
        description.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     */
    private JLabel title;
    
    private JLabel description;
    
    private JButton cmdConfirm;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
